// <auto-generated />
namespace Newsletter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstmigrationwithaddedIsAdminField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstmigrationwithaddedIsAdminField));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041233390_First migration with added IsAdminField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
