// <auto-generated />
namespace Newsletter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class try20addisSub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(try20addisSub));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181440401_try 2.0 add isSub"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
